Default group
cmintey/wishlist pull request #179
Opened 2024-11-29 11:58 UTC by albinmedoc

Closes #177

2024-11-29 12:00 UTC, albinmedoc commented
When this is merged, I will start working on Proxy Header authentication.

2024-11-29 13:42 UTC, albinmedoc commented
> When this is merged, I will start working on Proxy Header authentication.

I have to code ready for this as well. Will make a PR when this is merged, since it's based on this.

2024-11-30 18:38 UTC, cmintey commented
I'm back and forth between this being a setting, or if there should be a `default` flag on the group model itself. If we do it the way you have it now, then there would need to be an additional check to make sure the group exists (in case the default group was deleted). 
If we put it on the group model, then we could query directly for the default group. There would need to be additional logic when setting the default group to make sure we don't have multiple, but I think that's fine. Then the flag would live on the group settings page, and it can be displayed in the group table as well.

2024-11-30 18:38 UTC, cmintey commented
As for  your PR on proxy auth, can you open a separate feature request for that? I want to discuss it

2024-11-30 19:06 UTC, albinmedoc commented
> As for your PR on proxy auth, can you open a separate feature request for that? I want to discuss it

Opened in #180

2024-11-30 19:18 UTC, albinmedoc commented
I've committed a change that prevents the deletion of the default group. Since there can only be one default group, I believe the best approach is to store it globally and allow changes through the global settings. Additionally, I want to display the default group in the group table.

2024-12-01 16:15 UTC, cmintey commented
Cool, I think that's appropriate. Functionality is good! I'm going to merge another PR which will cause some conflicts on this branch, just FYI

2024-12-01 18:30 UTC, albinmedoc commented
I have resolved the conflicts

2024-12-01 19:53 UTC, cmintey requested changes
You should pass the groups to the `SettingsForm` in the `GlobalSettingsStep` component. You can pull the groups the same way as the config
```ts
let groups: Group[] = $state($page.data.groups);
```

2024-12-01 19:53 UTC, cmintey commented on src/lib/components/admin/SettingsForm/DefaultGroup.svelte
> +</div>
In the PR I merged earlier, it added a new `BaseSetting` component you can use here

2024-12-01 22:14 UTC, albinmedoc commented
It should be fixed now

2024-12-02 00:33 UTC, cmintey approved these changes
Looks good. Lint check is failing, you can fix the formatting issues by running `pnpm format`

2024-12-02 06:53 UTC, albinmedoc commented
I have now fixed the lint check

2024-12-02 14:22 UTC, merged